import createClient from "openapi-fetch";

import type { paths } from "@/lib/api/schema";

/**
 * The typed API client. Paths, query params, and response bodies are all typed from the
 * backend's OpenAPI (`paths` is generated by `npm run gen:api`).
 *
 * `baseUrl: ""` → same-origin relative requests (`/api/v1/...`); the Next rewrite in
 * next.config proxies them to FastAPI (prod: Nginx does the same). So the browser never
 * needs to know the API's real host, and there is no CORS.
 */
export const api = createClient<paths>({ baseUrl: "" });
