/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Readiness probe — 200 only if a round-trip to Postgres succeeds, else a clean 503.
         *
         *     The try/except here is justified: this is an infrastructure probe, not business logic,
         *     and translating a DB outage into a 503 is exactly the endpoint's job.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description KPI block + period-over-period deltas for the filtered window.
         */
        get: operations["get_summary_api_v1_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trend
         * @description Revenue/units time series, bucketed by `day` (default) or `week`.
         *
         *     `query` is a `TrendQuery` (an `AnalyticsFilters` + `bucket`), so it doubles as the
         *     filters object passed to the service.
         */
        get: operations["get_trend_api_v1_analytics_trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/metrics/{metric}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Metric Detail
         * @description Full drill-down for one KPI: its value + delta, day trend, and dimension breakdowns.
         *
         *     `metric` is typed as the `MetricKey` Literal, so an unknown metric is rejected with 422
         *     before any code runs (same self-validating pattern as `/breakdowns/{dimension}`).
         */
        get: operations["get_metric_detail_api_v1_analytics_metrics__metric__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/breakdowns/{dimension}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Breakdown
         * @description Top-N groups for `dimension` over the filtered window, with share%.
         */
        get: operations["get_breakdown_api_v1_breakdowns__dimension__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Products
         * @description Products ranked by revenue|units|returns, with image + variant count, paginated.
         */
        get: operations["list_products_api_v1_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Product
         * @description A single product and its per-variant sales over the filtered window.
         */
        get: operations["get_product_api_v1_products__product_code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Transactions
         * @description Filtered, sorted, paginated line items.
         */
        get: operations["list_transactions_api_v1_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/invoice/{invoice_no}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Invoice Detail
         * @description Every line item of one invoice, scoped to a date window so chunks are pruned.
         *     Optional `store` (associate name) disambiguates reused POS invoice numbers.
         */
        get: operations["get_invoice_detail_api_v1_transactions_invoice__invoice_no__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Typeahead hits across product code / SKU / invoice, within the date window.
         */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/filters/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Filter Options
         * @description Selectable values for stores / brands / categories / channels in the window.
         */
        get: operations["filter_options_api_v1_filters_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/filters/salespeople": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Salespeople
         * @description Cascade: staff with sales in the selected store(s); empty for EC-only.
         */
        get: operations["salespeople_api_v1_filters_salespeople_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/transactions.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Transactions
         * @description Stream the currently-filtered line items as a CSV download.
         */
        get: operations["export_transactions_api_v1_export_transactions_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Store Leaderboard
         * @description Every store's month-to-date KPIs (sale, projection, ATV/ASP/basket, discount%, WoW),
         *     ranked by MTD sale.
         */
        get: operations["get_store_leaderboard_api_v1_stores_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/hierarchy/{level}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Store Hierarchy
         * @description Current-month totals grouped by region / cluster / area-manager / regional-manager.
         */
        get: operations["get_store_hierarchy_api_v1_stores_hierarchy__level__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{store_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Store Detail
         * @description One store's detail over [dateFrom, dateTo]: KPIs + daily series + salesperson leaderboard.
         */
        get: operations["get_store_detail_api_v1_stores__store_code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BreakdownItem
         * @description One group of the breakdown (e.g. one store, one category).
         */
        BreakdownItem: {
            /** Label */
            label: string;
            /** Netrevenue */
            netRevenue: number;
            /** Units */
            units: number;
            /** Share */
            share: number;
        };
        /** BreakdownResponse */
        BreakdownResponse: {
            /** Dimension */
            dimension: string;
            /** Totalnetrevenue */
            totalNetRevenue: number;
            /** Items */
            items: components["schemas"]["BreakdownItem"][];
        };
        /**
         * FilterOptionsResponse
         * @description Selectable values for each multi-select dimension, scoped to the date window.
         */
        FilterOptionsResponse: {
            /** Stores */
            stores: components["schemas"]["StoreOptionOut"][];
            /** Brands */
            brands: string[];
            /** Categories */
            categories: string[];
            /** Channels */
            channels: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HierarchyResponse */
        HierarchyResponse: {
            /** Level */
            level: string;
            /** Asof */
            asOf?: string | null;
            /** Items */
            items: components["schemas"]["HierarchyRow"][];
        };
        /**
         * HierarchyRow
         * @description One hierarchy group (region / cluster / a manager) rolled up across its stores.
         */
        HierarchyRow: {
            /** Label */
            label: string;
            /** Nsv */
            nsv: number;
            /** Billcnt */
            billCnt: number;
            /** Qty */
            qty: number;
            /** Storecount */
            storeCount: number;
            /** Atv */
            atv: number;
        };
        /**
         * InvoiceDetailResponse
         * @description A full invoice: header (store/channel/customer/date/totals) + its line items.
         */
        InvoiceDetailResponse: {
            /** Invoiceno */
            invoiceNo: string;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Store */
            store: string | null;
            /** Channel */
            channel: string | null;
            /** Customer */
            customer: string | null;
            /** Mobile */
            mobile: string | null;
            /** Salesperson */
            salesperson: string | null;
            /** Totalnet */
            totalNet: number;
            /** Totalqty */
            totalQty: number;
            /** Linecount */
            lineCount: number;
            /** Lines */
            lines: components["schemas"]["InvoiceLine"][];
        };
        /**
         * InvoiceLine
         * @description One line item on the bill (the header carries the shared store/customer/date).
         */
        InvoiceLine: {
            /** Productcode */
            productCode: string | null;
            /** Imageurl */
            imageUrl?: string | null;
            /** Sku */
            sku: string | null;
            /** Category */
            category: string | null;
            /** Brand */
            brand: string | null;
            /** Qty */
            qty: number;
            /** Mrp */
            mrp: number;
            /** Discount */
            discount: number;
            /** Net */
            net: number;
        };
        /**
         * KpiDelta
         * @description Period-over-period change for one metric (vs the previous equal-length window).
         */
        KpiDelta: {
            /** Current */
            current: number;
            /** Previous */
            previous?: number | null;
            /** Pctchange */
            pctChange?: number | null;
        };
        /**
         * MetricBreakdownGroup
         * @description This metric grouped by one dimension (store / category / brand / channel …).
         */
        MetricBreakdownGroup: {
            /** Dimension */
            dimension: string;
            /** Items */
            items: components["schemas"]["MetricBreakdownItem"][];
        };
        /**
         * MetricBreakdownItem
         * @description One dimension group's value for this metric, with its share of the dimension total.
         *     `share` is None for non-additive metrics (distinct counts / ratios), where a share% would
         *     be misleading; the client omits the annotation when it is null.
         */
        MetricBreakdownItem: {
            /** Label */
            label: string;
            /** Value */
            value: number;
            /** Share */
            share?: number | null;
        };
        /**
         * MetricDetailResponse
         * @description Everything a single metric's detail page needs.
         */
        MetricDetailResponse: {
            /** Metric */
            metric: string;
            /** Label */
            label: string;
            /**
             * Unit
             * @enum {string}
             */
            unit: "currency" | "number" | "percent";
            /** Value */
            value: number;
            delta?: components["schemas"]["KpiDelta"] | null;
            /** Trend */
            trend: components["schemas"]["MetricPointOut"][];
            /** Breakdowns */
            breakdowns: components["schemas"]["MetricBreakdownGroup"][];
        };
        /**
         * MetricPointOut
         * @description One time bucket of the metric (day granularity).
         */
        MetricPointOut: {
            /**
             * Bucket
             * Format: date
             */
            bucket: string;
            /** Value */
            value: number;
        };
        /** Page[ProductCard] */
        Page_ProductCard_: {
            /** Items */
            items: components["schemas"]["ProductCard"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Pages */
            pages: number;
        };
        /** Page[TransactionRowOut] */
        Page_TransactionRowOut_: {
            /** Items */
            items: components["schemas"]["TransactionRowOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Pages */
            pages: number;
        };
        /**
         * ProductCard
         * @description One product tile in the gallery.
         */
        ProductCard: {
            /** Productcode */
            productCode: string;
            /** Category */
            category: string;
            /** Imageurl */
            imageUrl: string | null;
            /** Variantcount */
            variantCount: number;
            /** Netrevenue */
            netRevenue: number;
            /** Units */
            units: number;
            /** Returnsunits */
            returnsUnits: number;
        };
        /**
         * ProductDetail
         * @description A single product with its variants, for the drill-down view.
         */
        ProductDetail: {
            /** Productcode */
            productCode: string;
            /** Imageurl */
            imageUrl: string | null;
            /** Variantcount */
            variantCount: number;
            /** Netrevenue */
            netRevenue: number;
            /** Units */
            units: number;
            /** Variants */
            variants: components["schemas"]["VariantItem"][];
        };
        /** SalespersonOption */
        SalespersonOption: {
            /** Code */
            code: string;
            /** Name */
            name: string | null;
            /** Count */
            count: number;
        };
        /** SalespersonsResponse */
        SalespersonsResponse: {
            /** Salespersons */
            salespersons: components["schemas"]["SalespersonOption"][];
        };
        /** SearchHitOut */
        SearchHitOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "product" | "sku" | "invoice";
            /** Value */
            value: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Hits */
            hits: components["schemas"]["SearchHitOut"][];
        };
        /**
         * StoreDayPoint
         * @description One day of a store's series.
         */
        StoreDayPoint: {
            /**
             * Bucket
             * Format: date
             */
            bucket: string;
            /** Nsv */
            nsv: number;
            /** Billcnt */
            billCnt: number;
            /** Qty */
            qty: number;
            /** Returns */
            returns: number;
        };
        /**
         * StoreDetailResponse
         * @description One store's detail for the selected window: header + KPIs + daily series + staff.
         */
        StoreDetailResponse: {
            /** Storecode */
            storeCode: string;
            /** Storename */
            storeName: string | null;
            /** Storetype */
            storeType: string | null;
            /** Region */
            region: string | null;
            /** State */
            state: string | null;
            /** City */
            city: string | null;
            /** Cluster */
            cluster: string | null;
            /** Storemanager */
            storeManager: string | null;
            /** Clustermanager */
            clusterManager: string | null;
            /** Areamanager */
            areaManager: string | null;
            /** Regionalmanager */
            regionalManager: string | null;
            /** Nsv */
            nsv: number;
            /** Gsv */
            gsv: number;
            /** Mrp */
            mrp: number;
            /** Discount */
            discount: number;
            /** Discpct */
            discPct: number;
            /** Billcnt */
            billCnt: number;
            /** Qty */
            qty: number;
            /** Returns */
            returns: number;
            /** Atv */
            atv: number;
            /** Asp */
            asp: number;
            /** Basket */
            basket: number;
            /** Opday */
            opDay: number;
            /** Avgsale */
            avgSale: number;
            /** Trend */
            trend: components["schemas"]["StoreDayPoint"][];
            /** Salespeople */
            salespeople: components["schemas"]["StorePersonRow"][];
        };
        /**
         * StoreLeaderboardResponse
         * @description Current-month store leaderboard, ranked by MTD sale.
         */
        StoreLeaderboardResponse: {
            /** Asof */
            asOf?: string | null;
            /** Items */
            items: components["schemas"]["StoreMtdRow"][];
        };
        /**
         * StoreMtdRow
         * @description One store's month-to-date performance row for the leaderboard.
         */
        StoreMtdRow: {
            /** Storecode */
            storeCode: string;
            /** Storename */
            storeName: string | null;
            /** Storetype */
            storeType: string | null;
            /** Region */
            region: string | null;
            /** State */
            state: string | null;
            /** City */
            city: string | null;
            /** Cluster */
            cluster: string | null;
            /** Storemanager */
            storeManager: string | null;
            /** Clustermanager */
            clusterManager: string | null;
            /** Areamanager */
            areaManager: string | null;
            /** Regionalmanager */
            regionalManager: string | null;
            /** Mtdsale */
            mtdSale: number;
            /** Grossmrp */
            grossMrp: number;
            /** Discpct */
            discPct: number;
            /** Billcnt */
            billCnt: number;
            /** Qty */
            qty: number;
            /** Returns */
            returns: number;
            /** Basket */
            basket: number;
            /** Atv */
            atv: number;
            /** Asp */
            asp: number;
            /** Opday */
            opDay: number;
            /** Avgsale */
            avgSale: number;
            /** Projectionsale */
            projectionSale: number;
            /** Wowbill */
            wowBill: number;
            /** Wowbillnsv */
            wowBillNsv: number;
        };
        /** StoreOptionOut */
        StoreOptionOut: {
            /** Code */
            code: string;
            /** Name */
            name: string | null;
        };
        /**
         * StorePersonRow
         * @description One salesperson's totals within a store.
         */
        StorePersonRow: {
            /** Code */
            code: string;
            /** Name */
            name: string | null;
            /** Nsv */
            nsv: number;
            /** Billcnt */
            billCnt: number;
            /** Qty */
            qty: number;
            /** Atv */
            atv: number;
        };
        /**
         * SummaryResponse
         * @description The KPI block (SPEC §3). Deltas are attached for the headline metrics.
         */
        SummaryResponse: {
            /** Netrevenue */
            netRevenue: number;
            /** Grosssales */
            grossSales: number;
            /** Returnsvalue */
            returnsValue: number;
            /** Unitssold */
            unitsSold: number;
            /** Unitsreturned */
            unitsReturned: number;
            /** Invoices */
            invoices: number;
            /** Customers */
            customers: number;
            /** Discountrate */
            discountRate: number;
            netRevenueDelta?: components["schemas"]["KpiDelta"] | null;
            invoicesDelta?: components["schemas"]["KpiDelta"] | null;
        };
        /**
         * TransactionRowOut
         * @description One line item row in the table. `first_bill_date` is kept raw (SPEC).
         */
        TransactionRowOut: {
            /**
             * Invoicedate
             * Format: date-time
             */
            invoiceDate: string;
            /** Invoiceno */
            invoiceNo: string | null;
            /** Productcode */
            productCode: string | null;
            /** Sku */
            sku: string | null;
            /** Store */
            store: string | null;
            /** Channel */
            channel: string | null;
            /** Category */
            category: string | null;
            /** Brand */
            brand: string | null;
            /** Qty */
            qty: number;
            /** Mrp */
            mrp: number;
            /** Discount */
            discount: number;
            /** Net */
            net: number;
            /** Salesperson */
            salesperson: string | null;
            /** Customer */
            customer: string | null;
            /** Mobile */
            mobile: string | null;
            /** Firstbilldate */
            firstBillDate: string | null;
        };
        /**
         * TrendPointOut
         * @description One day/week bucket of the trend. Built from a repo `TrendPoint` via
         *     `from_attributes` (field names line up: bucket / net_revenue / units).
         */
        TrendPointOut: {
            /**
             * Bucket
             * Format: date
             */
            bucket: string;
            /** Netrevenue */
            netRevenue: number;
            /** Units */
            units: number;
        };
        /**
         * TrendResponse
         * @description The trend series plus which bucket size produced it.
         */
        TrendResponse: {
            /**
             * Bucket
             * @enum {string}
             */
            bucket: "day" | "week";
            /** Points */
            points: components["schemas"]["TrendPointOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VariantItem
         * @description One size/variant of a product (drill-down).
         */
        VariantItem: {
            /** Sku */
            sku: string;
            /** Netrevenue */
            netRevenue: number;
            /** Units */
            units: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_summary_api_v1_analytics_summary_get: {
        parameters: {
            query: {
                dateFrom: string;
                dateTo: string;
                stores?: string[];
                brands?: string[];
                categories?: string[];
                channels?: string[];
                salespersons?: string[];
                products?: string[];
                qtyMin?: number | null;
                qtyMax?: number | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trend_api_v1_analytics_trend_get: {
        parameters: {
            query: {
                dateFrom: string;
                dateTo: string;
                stores?: string[];
                brands?: string[];
                categories?: string[];
                channels?: string[];
                salespersons?: string[];
                products?: string[];
                qtyMin?: number | null;
                qtyMax?: number | null;
                search?: string | null;
                bucket?: "day" | "week";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metric_detail_api_v1_analytics_metrics__metric__get: {
        parameters: {
            query: {
                dateFrom: string;
                dateTo: string;
                stores?: string[];
                brands?: string[];
                categories?: string[];
                channels?: string[];
                salespersons?: string[];
                products?: string[];
                qtyMin?: number | null;
                qtyMax?: number | null;
                search?: string | null;
            };
            header?: never;
            path: {
                metric: "net_revenue" | "gross_sales" | "returns_value" | "units_sold" | "invoices" | "customers" | "discount_rate";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_breakdown_api_v1_breakdowns__dimension__get: {
        parameters: {
            query: {
                dateFrom: string;
                dateTo: string;
                stores?: string[];
                brands?: string[];
                categories?: string[];
                channels?: string[];
                salespersons?: string[];
                products?: string[];
                qtyMin?: number | null;
                qtyMax?: number | null;
                search?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                dimension: "store" | "category" | "brand" | "channel" | "salesperson" | "region" | "city" | "cluster";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BreakdownResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_products_api_v1_products_get: {
        parameters: {
            query: {
                dateFrom: string;
                dateTo: string;
                stores?: string[];
                brands?: string[];
                categories?: string[];
                channels?: string[];
                salespersons?: string[];
                products?: string[];
                qtyMin?: number | null;
                qtyMax?: number | null;
                search?: string | null;
                rankBy?: "revenue" | "units" | "returns";
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ProductCard_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_api_v1_products__product_code__get: {
        parameters: {
            query: {
                dateFrom: string;
                dateTo: string;
                stores?: string[];
                brands?: string[];
                categories?: string[];
                channels?: string[];
                salespersons?: string[];
                products?: string[];
                qtyMin?: number | null;
                qtyMax?: number | null;
                search?: string | null;
            };
            header?: never;
            path: {
                product_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transactions_api_v1_transactions_get: {
        parameters: {
            query: {
                dateFrom: string;
                dateTo: string;
                stores?: string[];
                brands?: string[];
                categories?: string[];
                channels?: string[];
                salespersons?: string[];
                products?: string[];
                qtyMin?: number | null;
                qtyMax?: number | null;
                search?: string | null;
                page?: number;
                pageSize?: number;
                sortKey?: "date" | "invoice" | "product" | "sku" | "store" | "category" | "brand" | "qty" | "mrp" | "discount" | "net" | "salesperson";
                sortDir?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TransactionRowOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_invoice_detail_api_v1_transactions_invoice__invoice_no__get: {
        parameters: {
            query: {
                dateFrom: string;
                dateTo: string;
                store?: string | null;
            };
            header?: never;
            path: {
                invoice_no: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query: {
                dateFrom: string;
                dateTo: string;
                stores?: string[];
                brands?: string[];
                categories?: string[];
                channels?: string[];
                salespersons?: string[];
                products?: string[];
                qtyMin?: number | null;
                qtyMax?: number | null;
                search?: string | null;
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    filter_options_api_v1_filters_options_get: {
        parameters: {
            query: {
                dateFrom: string;
                dateTo: string;
                stores?: string[];
                brands?: string[];
                categories?: string[];
                channels?: string[];
                salespersons?: string[];
                products?: string[];
                qtyMin?: number | null;
                qtyMax?: number | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterOptionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    salespeople_api_v1_filters_salespeople_get: {
        parameters: {
            query: {
                dateFrom: string;
                dateTo: string;
                stores?: string[];
                brands?: string[];
                categories?: string[];
                channels?: string[];
                salespersons?: string[];
                products?: string[];
                qtyMin?: number | null;
                qtyMax?: number | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalespersonsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_transactions_api_v1_export_transactions_csv_get: {
        parameters: {
            query: {
                dateFrom: string;
                dateTo: string;
                stores?: string[];
                brands?: string[];
                categories?: string[];
                channels?: string[];
                salespersons?: string[];
                products?: string[];
                qtyMin?: number | null;
                qtyMax?: number | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_store_leaderboard_api_v1_stores_leaderboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreLeaderboardResponse"];
                };
            };
        };
    };
    get_store_hierarchy_api_v1_stores_hierarchy__level__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                level: "region" | "cluster" | "area_manager" | "regional_manager";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HierarchyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_store_detail_api_v1_stores__store_code__get: {
        parameters: {
            query: {
                dateFrom: string;
                dateTo: string;
            };
            header?: never;
            path: {
                store_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
